responces_gali = ['Aanguli kora',
					'Ami tor maa ke chudmu',
					'Baal chhero', 	
					'Bara',	
					'Beissha Magir Pola tui', 			
					'Bokachoda',
					'Chudanir pola',
					'Chudmu tor pasai sneha',
					'Chumu dao',
					'Dhon khecha tui',
					'Gaand Maara',
					'Khankir chele',
					'Shetar bal tui',
					'Thor heta muka ath boridimu',
					'Tor Gaar Maari',
					'Tor maa ke chudi',
					'Vuuski magi',
					'baal',
					'boltu chire felbo',
					'khankir pola tui',
					'lehr kawrar bachha',
					'pod marani',
					'tor mar vhoda',
					'tumi bal hagu koro!!',
					'Shuorer Naati',
					'Lakkhi Chhara',
					'Jhata-khaika',
					'Chechra',
					'Shoytaner Bachcha',
					'Kutni Mashi',
					'Ghute Kuruni',
					'Mukh Puri',
					'Gaach Bolod',
					'Kelane'
					'Maderchod',
					'Bhosadike',
					'Bhen chod',
					'Beti chod',
					'Bhadhava',
					'Chodu',
					'Chutiya','Gaand','Gaandu','Gadha','Lauda','Hijra','Kuttiya','Paad','Randi','Saala kutta','Saali kutti','Tatti','Kamina','Chut ke pasine mein talay huye bhajiye ','Chut ke dhakkan','Chut ke gulam ','Kali Choot Ke Safaid Jhaat ','Khotey ki aulda','Kutte ka awlat','Kutte ki jat ','Kutte ke tatte','teri maa ki choot','Lavde ke bal ','Lund Chus','Lund Ke Pasine ','Meri Gand Ka Khatmal','Moot ','Najayaz paidaish','Rundi khana','Sadi hui gaand','Teri gaand','main kute ka lund ','Teri maa ka bhosda ','Teri maa ki chut ','Tere gaand mein keede paday ','Ullu ke pathe']

kami_responces = ['ah yes it is i, Kami',
					'understandable',
					'ah yes the classic call',
					'thanks Araon-chan',
					'Yes',
					'Hello',
					'No',
					'How about no',
					'EZ Clap',
					'Eat Pant',
					'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
					'Left',
					'Right',
					'Goodnight']

choices = ['Head!',
		'Tails!']


responces_headpat = ['humpf','uwu','OwO','How dare you touch me you filthy twat','ok i\'ll let you this time']

responces_bot = ['yeah that\'s what they call you ingame','i\'m pretty sure everybody knows that already','yeah you\'re the one acting like a bot rn','at least i\'ll be here when you\'re not',
				'mereko na tujhse mu nahi lagna','abe chal be lavde','yes i\'m a BOT, you have a problem?','yes, i\'m a bot and yeah you pretty much addressed the elephant in the room']