responces_gali = ['Aanguli kora',
					'Ami tor maa ke chudmu',
					'Baal chhero', 	
					'Bara',	
					'Beissha Magir Pola tui', 			
					'Bokachoda',
					'Chudanir pola',
					'Chudmu tor pasai sneha',
					'Chumu dao',
					'Dhon khecha tui',
					'Gaand Maara',
					'Khankir chele',
					'Shetar bal tui',
					'Thor heta muka ath boridimu',
					'Tor Gaar Maari',
					'Tor maa ke chudi',
					'Vuuski magi',
					'baal',
					'boltu chire felbo',
					'khankir pola tui',
					'lehr kawrar bachha',
					'pod marani',
					'tor mar vhoda',
					'tumi bal hagu koro!!',
					'Shuorer Naati',
					'Lakkhi Chhara',
					'Jhata-khaika',
					'Chechra',
					'Shoytaner Bachcha',
					'Kutni Mashi',
					'Ghute Kuruni',
					'Mukh Puri',
					'Gaach Bolod',
					'Kelane']

kami_responces = ['ah yes it is i, Kami',
					'understandable',
					'ah yes the classic call',
					'thanks Araon-chan',
					'Yes',
					'Hello',
					'No',
					'How about no',
					'EZ Clap',
					'Eat Pant',
					'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
					'Left',
					'Right',
					'Goodnight']

choices = ['Head!',
		'Tails!']